server:
  port: 8090
---
queue:
  name: testqueue
  durable: true
  exclusive: false
  autoDelete: false
  args:
    x-message-ttl: 3600000
    x-max-length: 50000
    x-max-priority: 2
    x-queue-mode: lazy
---
spring:
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
    ssl.enabled:  false
    host: localhost
    port: 15672
    username: guest
    password: guest
    virtual-host: guest
    uri: amqp://guest:guest@localhost:15672/guest

